### ISSUE TITLE
Training the dataset  using Folder name as image Labels

### ISSUE THREAD

**Issue by ratanman** [ncoudray/DeepPATH#63]
Hello,
I have read in your repo that TCGA dataset are not annotated(only metadata+svs images). So we divide/sort(as mentioned) into folders LUSC,LUAD,Normal_Solid_Tissue. How does the model learn **without the annotations**? 

Forgive me if this is a trivial question: If there is no annotations then similar(tiles) features are clustered and then inferred. But here we are just classifying.

TFRecords are used to keep track of tiles with patient(full tissue image).

_So how is the model learn or some TF libraries doing the job?_

**Comment by ncoudray** [comment]
Hi - 
Not sure I understand your question. 

For this particular case, the annotation is per slide. Tiles' labels are the same as the slides. Due to high tumor content, this introduces only a small proportion of incorrectly labelled tiles. Tiles are saved in different folders and the folder name is taken as the label. Label's information is kept and handled by the conversion to TFRecord

If neeeded, there is way to assign labels per tile using xml files generated from Aperio imagescope annotations on slides. 

HTH,
Best
Nicolas
